name: docker

permissions:
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-saltstack-tester:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [22.04, 24.04]
        salt: [3006, 3007]
        include:
          - os: 22.04
            code: jammy
          - os: 24.04
            code: noble

    env:
      GIT_SHA: ${GITHUB_SHA::8}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Metadata
        id: docker_metadata
        uses: crazy-max/ghaction-docker-meta@v5
        with:
          images: |
            ghcr.io/ekristen/cast-tools/saltstack-tester
          tags: |
            type=raw,value=${{ matrix.os }}-${{ matrix.salt }}
            type=raw,value=${{ matrix.code }}-${{ matrix.salt }}
            type=raw,value=${{ matrix.os }}
            type=raw,value=${{ matrix.code }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./saltstack-tester
          file: ./saltstack-tester/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            SALTVERSION=${{ matrix.salt }}
            OSVERSION=${{ matrix.os }}
            OSCODE=${{ matrix.code }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          cache-to: type=inline
