name: docker

permissions:
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-saltstack-tester:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [noble, focal, jammy]
        salt: [3006, 3007]

    env:
      GIT_SHA: ${GITHUB_SHA::8}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Metadata
        id: docker_metadata
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ghcr.io/ekristen/cast-tools/saltstack-tester
          tags: |
            type=raw,value=${{ matrix.os }}-${{ matrix.salt }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./saltstack-tester
          file: ./saltstack-tester/Dockerfile.${{ matrix.os }}
          build-args: |
            SALTVERSION=${{ matrix.salt }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
